# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Test an image
      inputs:
        command: build
        buildContext: '$(Build.SourcesDirectory)'
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - script: |
        docker login -u $(Docker Username) -p $(Docker Token)
        docker tag $(Build.BuildId) $(Docker Username)/hsa:$(Build.BuildId)
        docker push $(Docker Username)/hsa:$(Build.BuildId)

