# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

pr: none

resources:
- repo: self

stages:
- stage: Test
  displayName: Test that SSH scripts are working correctly
  jobs:
  - job: DeployToK3s
    steps:
    - script: |
        # Create SSH directory
        mkdir -p ~/.ssh
        
        # Write private key to file
        echo "$(PRIVATE_KEY)" | tr -d '\r' > ~/.ssh/id_rsa
        
        # Set correct permissions
        chmod 600 ~/.ssh/id_rsa
        
        # Add known hosts
        ssh-keyscan -H $(SERVER_IP) >> ~/.ssh/known_hosts
      displayName: 'Prepare SSH Key'

    - script: |
        # SSH into remote server and deploy
        ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            root@$(SERVER_IP) \
            -p 22 \
            '
            wall hey
            
            
            '
      
