# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pr:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: Run Unit Tests
  jobs:
    - job: Test
      displayName: Test Frontend
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: Test an image
          inputs:
            command: build
            buildContext: '$(Build.SourcesDirectory)'
            dockerfile: '**/testing/frontend/Dockerfile'
            tags: |
              $(tag)
    - job: Test
      displayName: Test Backend
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: Test an image
          inputs:
            command: build
            buildContext: '$(Build.SourcesDirectory)'
            dockerfile: '**/testing/backend/Dockerfile'
            tags: |
              $(tag)