apiVersion: v1
kind: Service
metadata:
  name: hsa-app-service
spec:
  selector:
    app: hsa-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
